services:
  butantan-shield:
    container_name: aurora_butantan
    image: aurora/butantan-shield:local
    ports:
      - "8000:8000"
    networks:
      - aurora_network

  chronos-backoffice:
    container_name: aurora_chronos
    build:
      context: ..
      dockerfile: apps/chronos-backoffice/Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_CHRONOS_MODE=dev_local
      - SHIELD_URL=http://butantan-shield:8000
    depends_on:
      - butantan-shield
    networks:
      - aurora_network
    volumes:
      - ../apps/chronos-backoffice:/app
      - chronos_node_modules:/app/node_modules

networks:
  aurora_network:
    driver: bridge

volumes:
  chronos_node_modules: {}
